Keywords=["diaper", "product", "diapers", "only diapers", "brand diapers", 
    "brand of diapers", "her diaper", "every diaper", "baby diapers", 
    "any diaper", "no diaper", "brands of diapers", "only diaper", 
    "newborn diapers", "diapers since", "box of diapers", "new diaper", 
    "more diapers", "brand of diaper", "brand diaper", "amount of diapers",
    "some diapers", "these overnight diapers", "his diapers", 
    "new diapers", "diapers like", "first diaper", "diapering",
    "full diaper", "all diapers", "all the diapers", 
    "types of diapers", "each diaper", "one diaper",
    "their diaper", "any other diapers", "same diapers",
    "same diaper", "so many diapers", "6 diapers",
    "7 diapers", "5 diapers", "single diaper",
    "but the diapers", "1 diaper", 
    "diapers offer", 
    "baby diaper",
    "white diapers",
    "diapers really"]